apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: suvaatnbu/mern-backend:latest   # replace with your DockerHub image
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URL
          value: "mongodb://mongo-service:27017/mernapp"

